services:
  customer-postgres:
    container_name: customer-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customer
    volumes:
      - customer-postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - customer-postgres-net
    restart: unless-stopped

  fraud-postgres:
    container_name: fraud-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fraud
    volumes:
      - fraud-postgres:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - fraud-postgres-net
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@email.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin4}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - fraud-postgres-net
      - customer-postgres-net
    depends_on:
      - fraud-postgres
      - customer-postgres
    restart: unless-stopped

networks:
  customer-postgres-net:
    driver: bridge
  fraud-postgres-net:
    driver: bridge

volumes:
  customer-postgres:
  fraud-postgres:
  pgadmin: