server:
  port: 8081

spring:
  application:
    name: fraud-service

  datasource:
    url: jdbc:postgresql://fraud-postgres:5432/${DB_NAME:fraud}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
    fetch-registry: true
    register-with-eureka: true